language: android

jdk:
  - oraclejdk7

android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-google-m2repository
    - extra-android-m2repository

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# script for build and release via Travis to Bintray
#script: gradle/buildViaTravis.sh

notifications:
  email: false

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
env:
  matrix:
    - ANDROID_SDKS=android-19,sysimg-19  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
before_install:
  - pip install codecov
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
before_script:
  - ./ci/wait_for_emulator
  - adb shell input keyevent 82 &

after_success:
  - codecov